name: problem_solving_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  dsa_in_dart:
    git:
      url: https://github.com/Yazan-Abdalmutee/DSA-In-Dart.git

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
